### ISSUE TITLE
Connection lost with Tera switch every so often

### ISSUE THREAD

**Issue by ely105** [bitfocus/companion-module-draco-tera#4]
Hi,
  I have noticed on many occasions and completely different setups that the Bitfocus module seems to lose connection with the Tera switch.  There is a small red icon in the upper right of all the buttons that appear for a few seconds.  it usually goes away but for those few seconds it seems there is no connection or functionality with the Tera switch.  Have others noticed this? Any ideas on what may cause this?  This is a critical module in our setup and we really love that someone created this module for a KVM switch that is a little rare.  But would love to eliminate this small nagging issue if possible.  thanks!

**Comment by michaelmalice** [comment]
I just submitted a pull request with this bug fixed, along with port mode functionality added. Hopefully it will get merged soon.
